SmartSocial.Corporate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Configuration;
using ChargifyNET;
using ChargifyNET.Configuration;
using SmartSocial.Corporate.Models;

namespace SmartSocial.Corporate.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            ViewBag.Title = "Home Page";
            return View();
        }

        public ActionResult Services()
        {

            ViewBag.Title = "Our Services";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

       [HttpPost]
        public ActionResult ChargifyWebHook()
        {
            //ViewBag.Message = "Your contact page.";

            //var responseText=string.Empty;
            //ChargifyAccountRetrieverSection config = ConfigurationManager.GetSection("chargify") as ChargifyAccountRetrieverSection;
            //ChargifyAccountElement accountInfo = config.GetDefaultOrFirst();

            //HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(accountInfo.Site + "webhooks.format");
            //httpWebRequest.ContentType = "application/x-www-form-urlencoded";
            ////2.Pass the apikey and apipassword of chargify
            //httpWebRequest.Headers.Add("username:" + accountInfo.ApiKey);
            //httpWebRequest.Headers.Add("password:" + accountInfo.ApiPassword);
            ////3.pass basic authentication credentials
            //httpWebRequest.Credentials = new NetworkCredential(accountInfo.ApiKey, accountInfo.ApiPassword);
            ////4.Assign the httpWebRequest method ,here the method is GET
            //httpWebRequest.Method = "GET";


            ////https://domainname.chargify.com/

            //return View();

            WebhookEventData webHookdata = new WebhookEventData();
            webHookdata.@event = "signup_success";

            ChargifyAccountRetrieverSection config = ConfigurationManager.GetSection("chargify") as ChargifyAccountRetrieverSection;
            ChargifyAccountElement accountInfo = config.GetDefaultOrFirst();
            var sharedKey = accountInfo.SharedKey;

            var signatureHeaderHandle = "X-Chargify-Webhook-Signature-Hmac-Sha-256";
            //string signature = !string.IsNullOrEmpty(signature_hmac_sha_256) ? signature_hmac_sha_256 : this.Request.Headers[signatureHeaderHandle]; // Try and get the signature passed in the request header

            //ChargifyAccountRetrieverSection config = ConfigurationManager.GetSection("chargify") as ChargifyAccountRetrieverSection;
            //ChargifyAccountElement accountInfo = config.GetDefaultOrFirst();

            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(accountInfo.Site + "webhooks.json");
            httpWebRequest.ContentType = "application/x-www-form-urlencoded";
            //2.Pass the apikey and apipassword of chargify
            httpWebRequest.Headers.Add("username:" + accountInfo.ApiKey);
            httpWebRequest.Headers.Add("password:" + accountInfo.ApiPassword);
            //3.pass basic authentication credentials
            httpWebRequest.Credentials = new NetworkCredential(accountInfo.ApiKey, accountInfo.ApiPassword);
            //4.Assign the httpWebRequest method ,here the method is GET
            httpWebRequest.Method = "GET";
            
            
           // var isRequestValid = this.Request.InputStream.IsWebhookRequestValid(sharedKey, signature);

            //if (!isRequestValid) { return new HttpStatusCodeResult(HttpStatusCode.NotAcceptable, "Signature mismatch"); }

            switch (webHookdata.@event)
            {
                case "signup_success":
                    break;
                case "signup_failure":
                    break;
                case "renewal_success":
                    break;
                case "renewal_failure":
                    break;
                case "payment_success":
                    break;
                case "payment_failure":
                    break;
                case "billing_date_change":
                    break;
                case "subscription_state_change":
                    break;
                case "subscription_product_change":
                    break;
                case "subscription_card_update":
                    break;
                case "expiring_card":
                    break;
                case "customer_update":
                    break;
                case "component_allocation_change":
                    break;
                case "metered_usage":
                    break;
                case "upgrade_downgrade_sucess":
                    break;
                case "upgrade_downgrade_failure":
                    break;
                case "refund_success":
                    break;
                case "refund_failure":
                    break;
                case "upcoming_renewal_notice":
                    break;
                case "end_of_trial_notice":
                    break;
                case "statement_closed":
                    break;
                case "statement_settled":
                    break;
                case "expiration_date_change":
                    break;
                default:
                    break;
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

SmartSocial.Corporate/Controllers/IntakeController.cs
using SmartSocialServices.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartSocial.Corporate.Controllers
{
    public class IntakeController : Controller
    {
        LeadService _leadService = new LeadService();

        public ActionResult MoreInformation()
        {

            return View();

        }
        public ActionResult Subscribe(string ProductType)
        {
            return View();
        }

        [HttpGet]
        public JsonResult Load1stLeadPart(string strToken)
        {
            return Json(_leadService.GetLeadByToken(strToken), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Load1stLeadPartChargify(string subscription_id, string customer_id)
        {
            return Json(_leadService.ChargifySuscription(subscription_id, customer_id), JsonRequestBehavior.AllowGet);
        }

        public ActionResult SuccessSubscription(string subscription_id, string customer_id, string customer_reference)
        {
            _leadService.CreateUser(subscription_id, customer_id, customer_reference);
            return View("");
        }
    }
}

SmartSocial.Corporate/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

SmartSocial.Corporate/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

SmartSocial.Corporate/Views/Home/Services.cshtml
<div id="content">
    <!-- #content -->
    <!-- SECTION START -->
    <section class="services-preview white-bg mt20">
        <div class="container">
            <div class="row service-panel style1">
                <!-- .row start -->
                <div class="col-md-4">
                    <!-- col-md-4 start here -->
                    <div class="service-panel-heading">
                        <i class="l-basic-clock color-red"></i>
                        <h4>SOCIAL LISTENING ON TIME</h4>
                    </div>
                    <div class="service-panel-content">
                        <p>Our team works quickly to make sure you listen to what social networks have to tell you on time!</p>
                    </div>
                </div>
                <!-- col-md-4 end here -->
                <div class="col-md-4">
                    <!-- col-md-4 start here -->
                    <div class="service-panel-heading">
                        <i class="l-basic-heart color-red"></i>
                        <h4>We want you to succeed</h4>
                    </div>
                    <div class="service-panel-content">
                        <p>We love to provide real value for you, we want you to succeed!</p>
                    </div>
                </div>
                <!-- col-md-4 end here -->
                <div class="col-md-4">
                    <!-- col-md-4 start here -->
                    <div class="service-panel-heading">
                        <i class="l-basic-gear color-red"></i>
                        <h4>Flexible options</h4>
                    </div>
                    <div class="service-panel-content">
                        <p>Let us know how we can serve you better, our commitment to make a difference for our customers is complete!</p>
                    </div>
                </div>
                <!-- col-md-4 end here -->
                
            </div>
            <!-- / .row -->
        </div>
    </section>
    <!-- / SECTION END -->
    <!-- SECTION START -->
    <section class="services-preview gray-lighter-bg">
        <div class="container">
            <!-- .container -->
            <div class="row">
                <!-- .row start -->
                <div class="heading mt30 mb30 text-center">
                    <h3>Pricing</h3>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <!-- col-lg-3 start here -->
                    <div class="pricing-table">
                        <div class="pricing-header">
                            <h3>Trial</h3>
                        </div>
                        <ul class="list-group">
                            
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Customer Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Competitive Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Market Segment Report</li>
                            <li class="list-group-item "><i class="glyphicon glyphicon-share s24"></i> Unlimited Report Sharing</li>
                            <li class="list-group-item "><i class="glyphicon glyphicon-user s24"></i> 1 user</li>
                            <li class="list-group-item " style="visibility:hidden"><i class="glyphicon glyphicon-globe s24"></i> Custom Reports</li>
                            
                        </ul>
                        <div class="pricing-bottom clearfix">
                            <div class="price">
                                <span>0$</span>
                                / 30 days
                                @Html.ActionLink("Start your trial", "Subscribe", "Intake", new { ProductType = "Trial" }, new { @class = "btn btn-danger btn-lg btn-block" }) 
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col-lg-3 end here -->

                <div class="col-lg-4 col-md-4 col-sm-6">
                    <!-- col-lg-3 start here -->
                    <div class="pricing-table">
                        <div class="pricing-header">
                            <h3>Economic</h3>
                        </div>
                        <ul class="list-group">
                            
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Customer Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Competitive Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Market Segment Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-share s24"></i> Unlimited Report Sharing</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-user s24"></i> Up to 10 users</li>
                            
                            <li class="list-group-item" style="visibility:hidden"><i class="glyphicon glyphicon-globe s24"></i> Custom Reports</li>
                            
                        </ul>
                        <div class="pricing-bottom clearfix">
                            <div class="price">
                                <span>499$</span>
                                / month
                                @Html.ActionLink("Order Now", "Subscribe", "Intake", new { ProductType = "Economic" }, new { @class = "btn btn-danger btn-lg btn-block" })
                                
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col-lg-3 end here -->
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <!-- col-lg-3 start here -->
                    <div class="pricing-table">
                        <div class="pricing-header">
                            <h3>Business</h3>
                        </div>
                        <ul class="list-group">
                            
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Customer Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Competitive Report</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-signal s24"></i> A Market Segment Report</li>
                            
                            <li class="list-group-item"><i class="glyphicon glyphicon-share s24"></i> Unlimited Report Sharing</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-user s24"></i> Up to 50 company users</li>
                            <li class="list-group-item"><i class="glyphicon glyphicon-globe s24"></i><b> Customized Report</b></li>
                            
                        </ul>
                        <div class="pricing-bottom clearfix">
                            <div class="price">
                                <span>999$</span>
                                / month
                                @Html.ActionLink("Order Now", "Subscribe", "Intake", new { ProductType = "Business" }, new { @class = "btn btn-danger btn-lg btn-block" })
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col-lg-3 end here -->
            </div>
            <!-- / .row -->
        </div>
        <!-- / .container -->
    </section>
    <!-- / SECTION END -->
</div>
<!-- / #content -->
<div id="overlay" class="overlay"></div>